[package]
name = "nibblit"
description = "Check equality for nibble literals and bit literals."
authors = ["Shane Celis <shane.celis@gmail.com>"]
version = "0.1.0"
license = "MIT OR Apache-2.0"
edition = "2021"
keywords = ["bitmap", "literal", "hex", "test", "assert"]
readme = "README.md"
documentation = "https://docs.rs/nibblit"
repository = "https://github.com/shanecelis/nibblit"
categories = ["development-tools::testing"]

[package.metadata.docs.rs]
all-features = true
