[package]
name = "bitlit"
description = "Check equality for bitmap literals and hexmap literals."
authors = ["Shane Celis <shane.celis@gmail.com>"]
version = "0.1.0"
license = "MIT OR Apache-2.0"
edition = "2021"
keywords = ["bitmap", "literal", "hex", "test", "assert"]
readme = "README.md"
documentation = "https://docs.rs/bitlit"
repository = "https://github.com/shanecelis/bitlit"
categories = ["development-tools::testing"]

[package.metadata.docs.rs]
all-features = true
